repository_type: pipeline
lint:
  pipeline_todos: false
  files_unchanged: false
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-bulkrna_logo_light.png
    - docs/images/nf-core-bulkrna_logo_light.png
    - docs/images/nf-core-bulkrna_logo_dark.png
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - conf/test_full.config
  nextflow_config:
    - manifest.name
    - manifest.homePage
  multiqc_config:
    - report_comment
