contact_links:
  - name: Join nf-core
    url: https://nf-co.re/join
    about: Please join the nf-core community here
  - name: "Slack #dalmolingroup-bulkrna channel"
    url: https://nfcore.slack.com/channels/dalmolingroup-bulkrna
    about: Discussion about the nf-core/dalmolingroup-bulkrna pipeline
